services:
  # Backend Spring Boot
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  # Frontend Angular
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
